//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectStages
    {
        public int idStageProject { get; set; }
        public Nullable<int> idProject { get; set; }
        public string nameState { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public Nullable<int> idStatusStage { get; set; }
        public string descriptionStage { get; set; }
    
        public virtual Projects Projects { get; set; }
        public virtual ProjectStateStatuses ProjectStateStatuses { get; set; }
    }
}
