//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccount
    {
        public int idUserAccount { get; set; }
        public int idUser { get; set; }
        public string username { get; set; }
        public string passwordHash { get; set; }
        public Nullable<int> idRole { get; set; }
    
        public virtual UserRoles UserRoles { get; set; }
        public virtual Users Users { get; set; }
    }
}
