//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Документы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Документы()
        {
            this.ОтветственныеЗаДокумент = new HashSet<ОтветственныеЗаДокумент>();
            this.СогласующиеДокумент = new HashSet<СогласующиеДокумент>();
            this.ЭтапыДокументов = new HashSet<ЭтапыДокументов>();
        }
    
        public int ДокументID { get; set; }
        public string НазваниеДокумента { get; set; }
        public int ТипДокументаID { get; set; }
        public string Категория { get; set; }
        public System.DateTime ДатаСоздания { get; set; }
        public string Описание { get; set; }
        public int СтатусДокументаID { get; set; }
        public byte[] Содержание { get; set; }
        public int СозданоПользователемID { get; set; }
    
        public virtual Пользователи Пользователи { get; set; }
        public virtual СтатусыДокументов СтатусыДокументов { get; set; }
        public virtual ТипыДокументов ТипыДокументов { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ОтветственныеЗаДокумент> ОтветственныеЗаДокумент { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СогласующиеДокумент> СогласующиеДокумент { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ЭтапыДокументов> ЭтапыДокументов { get; set; }
    }
}
