//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Мероприятия
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Мероприятия()
        {
            this.ОтветственныеЗаМероприятие = new HashSet<ОтветственныеЗаМероприятие>();
            this.УчастникиМероприятия = new HashSet<УчастникиМероприятия>();
        }
    
        public int МероприятиеID { get; set; }
        public string НазваниеМероприятия { get; set; }
        public int ТипМероприятияID { get; set; }
        public int СтатусМероприятияID { get; set; }
        public System.DateTime ДатаНачала { get; set; }
        public System.DateTime ДатаОкончания { get; set; }
        public string КраткоеОписание { get; set; }
        public int ИнициаторID { get; set; }
    
        public virtual Пользователи Пользователи { get; set; }
        public virtual СтатусыМероприятий СтатусыМероприятий { get; set; }
        public virtual ТипыМероприятий ТипыМероприятий { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ОтветственныеЗаМероприятие> ОтветственныеЗаМероприятие { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<УчастникиМероприятия> УчастникиМероприятия { get; set; }
    }
}
