//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пользователи
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Пользователи()
        {
            this.Документы = new HashSet<Документы>();
            this.Мероприятия = new HashSet<Мероприятия>();
            this.Новости = new HashSet<Новости>();
            this.ОтветственныеЗаДокумент = new HashSet<ОтветственныеЗаДокумент>();
            this.ОтветственныеЗаМероприятие = new HashSet<ОтветственныеЗаМероприятие>();
            this.Подразделения = new HashSet<Подразделения>();
            this.Подразделения1 = new HashSet<Подразделения>();
            this.Пользователи1 = new HashSet<Пользователи>();
            this.Проекты = new HashSet<Проекты>();
            this.СобытияОтсутствия = new HashSet<СобытияОтсутствия>();
            this.СогласующиеДокумент = new HashSet<СогласующиеДокумент>();
            this.УчастникиМероприятия = new HashSet<УчастникиМероприятия>();
            this.Проекты1 = new HashSet<Проекты>();
        }
    
        public int ПользовательID { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
        public string Имя { get; set; }
        public string Фамилия { get; set; }
        public string Отчество { get; set; }
        public string ЭлПочта { get; set; }
        public int РольID { get; set; }
        public Nullable<int> ПодразделениеID { get; set; }
        public string Должность { get; set; }
        public string РабочийТелефон { get; set; }
        public string ДомашнийТелефон { get; set; }
        public Nullable<System.DateTime> ДатаРождения { get; set; }
        public Nullable<int> РуководительID { get; set; }
        public Nullable<int> ЗаменяющийID { get; set; }
        public string ПутьКФото { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Документы> Документы { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Мероприятия> Мероприятия { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Новости> Новости { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ОтветственныеЗаДокумент> ОтветственныеЗаДокумент { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ОтветственныеЗаМероприятие> ОтветственныеЗаМероприятие { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Подразделения> Подразделения { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Подразделения> Подразделения1 { get; set; }
        public virtual Подразделения Подразделения2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Пользователи> Пользователи1 { get; set; }
        public virtual Пользователи Пользователи2 { get; set; }
        public virtual Роли Роли { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Проекты> Проекты { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СобытияОтсутствия> СобытияОтсутствия { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СогласующиеДокумент> СогласующиеДокумент { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<УчастникиМероприятия> УчастникиМероприятия { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Проекты> Проекты1 { get; set; }
    }
}
