//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Проекты
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Проекты()
        {
            this.ЭтапыПроектов = new HashSet<ЭтапыПроектов>();
            this.Пользователи1 = new HashSet<Пользователи>();
        }
    
        public int ПроектID { get; set; }
        public string НазваниеПроекта { get; set; }
        public string ОписаниеПроекта { get; set; }
        public System.DateTime ДатаНачала { get; set; }
        public Nullable<System.DateTime> ДатаОкончания { get; set; }
        public int РуководительПроектаID { get; set; }
        public string Статус { get; set; }
    
        public virtual Пользователи Пользователи { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ЭтапыПроектов> ЭтапыПроектов { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Пользователи> Пользователи1 { get; set; }
    }
}
