//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class СобытияОтсутствия
    {
        public int СобытиеID { get; set; }
        public int ПользовательID { get; set; }
        public string ТипСобытия { get; set; }
        public System.DateTime ДатаНачала { get; set; }
        public Nullable<System.DateTime> ДатаОкончания { get; set; }
        public string Описание { get; set; }
        public string Место { get; set; }
    
        public virtual Пользователи Пользователи { get; set; }
    }
}
