//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ЭтапыПроектов
    {
        public int ЭтапID { get; set; }
        public int ПроектID { get; set; }
        public string НазваниеЭтапа { get; set; }
        public System.DateTime ДатаНачалаЭтапа { get; set; }
        public Nullable<System.DateTime> ДатаОкончанияЭтапа { get; set; }
        public string ТекущийСтатус { get; set; }
        public string ОписаниеЭтапа { get; set; }
    
        public virtual Проекты Проекты { get; set; }
    }
}
